### ISSUE TITLE
Model name update

### ISSUE THREAD

**Issue by vatiacg84** [Piotr1215/aicmdtools#2]
Hello.

I got this:

~/aicmdtools/scripts$ aicmdtools "Tellmesomething."
Error processing command: ChatCompletion error: error, status code: 404, message: The model `gpt-4` does not exist or you do not have access to it.
Error executing command: ChatCompletion error: error, status code: 404, message: The model `gpt-4` does not exist or you do not have access to it.
~/aicmdtools/scripts$

In config.yaml: "model: gpt-3.5-turbo"
The "curl https://api.openai.com/v1/models -H "Authorization: Bearer ..." told me that this model is supported.

API key is OK.
When I remove the API key, the error message changes to missing API key.
When I go to https://platform.openai.com/api-keys I see the last used date is today. So the command use the API key, but somehow not know it is not GPT-4 perhaps?
What can be wrong?
Should I set somewhere other the model name too?
Why want it use the gpt-4 instead the configured model?
I am a free plan user on OpenAI. I had a prepaid plan, but now there is no. Can it cause it? A thought gpt3.5 can be used with free account.

**Comment by Piotr1215** [comment]
:wave: @vatiacg84, thanks for using the tool! I have released a new version with fixes so that it should passthrough any model that you have access to. Also added `-model` flag to the `aicmd` command so that you can check which model is being used for the command.

I've also improved README with better usage and install instructions. LMK if this fixes the issue.

**Comment by vatiacg84** [comment]
Thank you.
The model version is now correct and the display works well too.

**Comment by Piotr1215** [comment]
Closing as implemented.
